spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE:control_financiero}
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
  
  jpa:
    show-sql: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024

logging:
  level:
    root: INFO
    com.proyecto: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
